"""Initial schema with all 12 models

Revision ID: 16902f1b3614
Revises:
Create Date: 2026-01-18 06:38:33.841237+09:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "16902f1b3614"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organizations_code"), "organizations", ["code"], unique=True)
    op.create_index(
        op.f("ix_organizations_is_active"), "organizations", ["is_active"], unique=False
    )
    op.create_index(op.f("ix_organizations_name"), "organizations", ["name"], unique=False)
    op.create_index(
        "ix_organizations_name_active", "organizations", ["name", "is_active"], unique=False
    )
    op.create_table(
        "catalogs",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("sku_code", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("manufacturer", sa.String(length=255), nullable=False),
        sa.Column("model_number", sa.String(length=100), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "DRONE",
                "BATTERY",
                "CAMERA",
                "CONTROLLER",
                "SENSOR",
                "ACCESSORY",
                name="catalogcategory",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("specifications", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("weight_grams", sa.Integer(), nullable=True),
        sa.Column("max_flight_time_minutes", sa.Integer(), nullable=True),
        sa.Column("max_range_meters", sa.Integer(), nullable=True),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("spec_document_url", sa.String(length=500), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_catalogs_category"), "catalogs", ["category"], unique=False)
    op.create_index(
        "ix_catalogs_org_category_active",
        "catalogs",
        ["organization_id", "category", "is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_catalogs_organization_id"), "catalogs", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_catalogs_sku_code"), "catalogs", ["sku_code"], unique=False)
    op.create_table(
        "clients",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column("contact_name", sa.String(length=255), nullable=True),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("contact_phone", sa.String(length=50), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("billing_address", sa.Text(), nullable=True),
        sa.Column("tax_id", sa.String(length=100), nullable=True),
        sa.Column("payment_terms", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clients_organization_id"), "clients", ["organization_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "ADMIN",
                "MANAGER",
                "OPERATOR",
                "VIEWER",
                name="userrole",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    op.create_table(
        "equipments",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("serial_number", sa.String(length=100), nullable=False),
        sa.Column("internal_id", sa.String(length=50), nullable=True),
        sa.Column("nickname", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "STORED",
                "MAINTENANCE",
                "RETIRED",
                name="equipmentstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("purchase_date", sa.Date(), nullable=True),
        sa.Column("warranty_expiry_date", sa.Date(), nullable=True),
        sa.Column("last_maintenance_date", sa.Date(), nullable=True),
        sa.Column("next_maintenance_date", sa.Date(), nullable=True),
        sa.Column("total_flight_time_minutes", sa.Integer(), nullable=False),
        sa.Column("total_flight_count", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("qr_code", sa.String(length=500), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("catalog_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["catalog_id"], ["catalogs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_equipments_catalog_id"), "equipments", ["catalog_id"], unique=False)
    op.create_index(
        op.f("ix_equipments_organization_id"), "equipments", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_equipments_serial_number"), "equipments", ["serial_number"], unique=False
    )
    op.create_index(op.f("ix_equipments_status"), "equipments", ["status"], unique=False)
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PLANNING",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED",
                "ON_HOLD",
                name="projectstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("location", sa.Text(), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("budget", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("actual_cost", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_client_id"), "projects", ["client_id"], unique=False)
    op.create_index(
        op.f("ix_projects_organization_id"), "projects", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_projects_status"), "projects", ["status"], unique=False)
    op.create_table(
        "staff",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("employee_id", sa.String(length=50), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("emergency_contact", sa.String(length=255), nullable=True),
        sa.Column("emergency_phone", sa.String(length=50), nullable=True),
        sa.Column("hire_date", sa.Date(), nullable=True),
        sa.Column("department", sa.String(length=100), nullable=True),
        sa.Column("position", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_pilot", sa.Boolean(), nullable=False),
        sa.Column("is_maintenance_staff", sa.Boolean(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_staff_organization_id"), "staff", ["organization_id"], unique=False)
    op.create_index(op.f("ix_staff_user_id"), "staff", ["user_id"], unique=True)
    op.create_table(
        "flight_applications",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("application_number", sa.String(length=100), nullable=True),
        sa.Column("dips_reference_id", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "SUBMITTED",
                "UNDER_REVIEW",
                "APPROVED",
                "REJECTED",
                "CANCELLED",
                "EXPIRED",
                name="applicationstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "flight_category",
            sa.Enum(
                "CATEGORY_1",
                "CATEGORY_2",
                "CATEGORY_3",
                "OPEN",
                name="flightcategory",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("flight_area", sa.Text(), nullable=True),
        sa.Column("flight_altitude_max", sa.Integer(), nullable=True),
        sa.Column("flight_altitude_min", sa.Integer(), nullable=True),
        sa.Column("planned_start_date", sa.Date(), nullable=False),
        sa.Column("planned_end_date", sa.Date(), nullable=False),
        sa.Column("flight_time_start", sa.String(length=10), nullable=True),
        sa.Column("flight_time_end", sa.String(length=10), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approval_number", sa.String(length=100), nullable=True),
        sa.Column("approval_conditions", sa.Text(), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("application_document_url", sa.String(length=500), nullable=True),
        sa.Column("approval_document_url", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_flight_applications_application_number"),
        "flight_applications",
        ["application_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flight_applications_organization_id"),
        "flight_applications",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flight_applications_project_id"),
        "flight_applications",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flight_applications_status"), "flight_applications", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_flight_applications_valid_until"),
        "flight_applications",
        ["valid_until"],
        unique=False,
    )
    op.create_table(
        "flight_logs",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("flight_number", sa.String(length=50), nullable=True),
        sa.Column(
            "purpose",
            sa.Enum(
                "SURVEY",
                "INSPECTION",
                "PHOTOGRAPHY",
                "AGRICULTURE",
                "DELIVERY",
                "TRAINING",
                "MAINTENANCE",
                "OTHER",
                name="flightpurpose",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("takeoff_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("landing_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("flight_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("takeoff_location", sa.Text(), nullable=True),
        sa.Column("landing_location", sa.Text(), nullable=True),
        sa.Column("takeoff_latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("takeoff_longitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("landing_latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("landing_longitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("max_altitude_meters", sa.Integer(), nullable=True),
        sa.Column("max_distance_meters", sa.Integer(), nullable=True),
        sa.Column("flight_path_geojson", sa.Text(), nullable=True),
        sa.Column(
            "weather_condition",
            sa.Enum(
                "CLEAR",
                "CLOUDY",
                "PARTLY_CLOUDY",
                "RAINY",
                "WINDY",
                "FOG",
                name="weathercondition",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column("temperature_celsius", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("wind_speed_mps", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("humidity_percent", sa.Integer(), nullable=True),
        sa.Column("battery_start_percent", sa.Integer(), nullable=True),
        sa.Column("battery_end_percent", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("incidents", sa.Text(), nullable=True),
        sa.Column("equipment_id", sa.UUID(), nullable=False),
        sa.Column("pilot_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["equipment_id"], ["equipments.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["pilot_id"], ["staff.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_flight_logs_equipment_id"), "flight_logs", ["equipment_id"], unique=False
    )
    op.create_index(op.f("ix_flight_logs_pilot_id"), "flight_logs", ["pilot_id"], unique=False)
    op.create_index(op.f("ix_flight_logs_project_id"), "flight_logs", ["project_id"], unique=False)
    op.create_index(op.f("ix_flight_logs_purpose"), "flight_logs", ["purpose"], unique=False)
    op.create_table(
        "licenses",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "license_type",
            sa.Enum(
                "PILOT_BASIC",
                "PILOT_ADVANCED",
                "PILOT_INSTRUCTOR",
                "MAINTENANCE",
                "RADIO",
                "INSURANCE",
                "OTHER",
                name="licensetype",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("license_number", sa.String(length=100), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("issuing_authority", sa.String(length=255), nullable=True),
        sa.Column("issue_date", sa.Date(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("document_url", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("staff_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["staff_id"], ["staff.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_licenses_expiry_date"), "licenses", ["expiry_date"], unique=False)
    op.create_index(op.f("ix_licenses_license_type"), "licenses", ["license_type"], unique=False)
    op.create_index(op.f("ix_licenses_staff_id"), "licenses", ["staff_id"], unique=False)
    op.create_table(
        "maintenance_logs",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "maintenance_type",
            sa.Enum(
                "ROUTINE",
                "REPAIR",
                "INSPECTION",
                "CALIBRATION",
                "UPGRADE",
                "PARTS_REPLACEMENT",
                name="maintenancetype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED",
                "IN_PROGRESS",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="maintenancestatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("scheduled_date", sa.Date(), nullable=True),
        sa.Column("performed_date", sa.Date(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("checklist_items", sa.Text(), nullable=True),
        sa.Column("findings", sa.Text(), nullable=True),
        sa.Column("actions_taken", sa.Text(), nullable=True),
        sa.Column("parts_replaced", sa.Text(), nullable=True),
        sa.Column("labor_cost", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("parts_cost", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("total_cost", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("next_maintenance_date", sa.Date(), nullable=True),
        sa.Column("next_maintenance_notes", sa.Text(), nullable=True),
        sa.Column("document_urls", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("equipment_id", sa.UUID(), nullable=False),
        sa.Column("technician_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["equipment_id"], ["equipments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["technician_id"], ["staff.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_maintenance_logs_equipment_id"), "maintenance_logs", ["equipment_id"], unique=False
    )
    op.create_index(
        op.f("ix_maintenance_logs_maintenance_type"),
        "maintenance_logs",
        ["maintenance_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_maintenance_logs_scheduled_date"),
        "maintenance_logs",
        ["scheduled_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_maintenance_logs_status"), "maintenance_logs", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_maintenance_logs_technician_id"),
        "maintenance_logs",
        ["technician_id"],
        unique=False,
    )
    op.create_table(
        "project_assignments",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "PILOT",
                "COPILOT",
                "OBSERVER",
                "SUPERVISOR",
                "TECHNICIAN",
                name="assignmentrole",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_confirmed", sa.Boolean(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("staff_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["staff_id"], ["staff.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_project_assignments_project_id"),
        "project_assignments",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_assignments_staff_id"), "project_assignments", ["staff_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_project_assignments_staff_id"), table_name="project_assignments")
    op.drop_index(op.f("ix_project_assignments_project_id"), table_name="project_assignments")
    op.drop_table("project_assignments")
    op.drop_index(op.f("ix_maintenance_logs_technician_id"), table_name="maintenance_logs")
    op.drop_index(op.f("ix_maintenance_logs_status"), table_name="maintenance_logs")
    op.drop_index(op.f("ix_maintenance_logs_scheduled_date"), table_name="maintenance_logs")
    op.drop_index(op.f("ix_maintenance_logs_maintenance_type"), table_name="maintenance_logs")
    op.drop_index(op.f("ix_maintenance_logs_equipment_id"), table_name="maintenance_logs")
    op.drop_table("maintenance_logs")
    op.drop_index(op.f("ix_licenses_staff_id"), table_name="licenses")
    op.drop_index(op.f("ix_licenses_license_type"), table_name="licenses")
    op.drop_index(op.f("ix_licenses_expiry_date"), table_name="licenses")
    op.drop_table("licenses")
    op.drop_index(op.f("ix_flight_logs_purpose"), table_name="flight_logs")
    op.drop_index(op.f("ix_flight_logs_project_id"), table_name="flight_logs")
    op.drop_index(op.f("ix_flight_logs_pilot_id"), table_name="flight_logs")
    op.drop_index(op.f("ix_flight_logs_equipment_id"), table_name="flight_logs")
    op.drop_table("flight_logs")
    op.drop_index(op.f("ix_flight_applications_valid_until"), table_name="flight_applications")
    op.drop_index(op.f("ix_flight_applications_status"), table_name="flight_applications")
    op.drop_index(op.f("ix_flight_applications_project_id"), table_name="flight_applications")
    op.drop_index(op.f("ix_flight_applications_organization_id"), table_name="flight_applications")
    op.drop_index(
        op.f("ix_flight_applications_application_number"), table_name="flight_applications"
    )
    op.drop_table("flight_applications")
    op.drop_index(op.f("ix_staff_user_id"), table_name="staff")
    op.drop_index(op.f("ix_staff_organization_id"), table_name="staff")
    op.drop_table("staff")
    op.drop_index(op.f("ix_projects_status"), table_name="projects")
    op.drop_index(op.f("ix_projects_organization_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_client_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_equipments_status"), table_name="equipments")
    op.drop_index(op.f("ix_equipments_serial_number"), table_name="equipments")
    op.drop_index(op.f("ix_equipments_organization_id"), table_name="equipments")
    op.drop_index(op.f("ix_equipments_catalog_id"), table_name="equipments")
    op.drop_table("equipments")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_clients_organization_id"), table_name="clients")
    op.drop_table("clients")
    op.drop_index(op.f("ix_catalogs_sku_code"), table_name="catalogs")
    op.drop_index(op.f("ix_catalogs_organization_id"), table_name="catalogs")
    op.drop_index("ix_catalogs_org_category_active", table_name="catalogs")
    op.drop_index(op.f("ix_catalogs_category"), table_name="catalogs")
    op.drop_table("catalogs")
    op.drop_index("ix_organizations_name_active", table_name="organizations")
    op.drop_index(op.f("ix_organizations_name"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_is_active"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_code"), table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
